### ISSUE TITLE
为什么注入不了内存马，冰蝎蚂蚁都不行，说是换目录也不行，怎么办呢？

### ISSUE THREAD

**Issue by wjl110** [SummerSec/ShiroAttack2#11]

**Comment by SummerSec** [comment]
这个具体原因有很多种可能性，本来打算写一篇教程。根据自己的经验，但一直被鸽了。主要原因就因为现在没有一个通用内存马解决方案

**Comment by Mulburryrelic63** [comment]
thanks

**Comment by Mulburryrelic63** [comment]
thanks> 这个具体原因有很多种可能性，本来打算写一篇教程。根据自己的经验，但一直被鸽了。主要原因就因为现在没有一个通用内存马解决方案
