### ISSUE TITLE
无法爆破密钥

### ISSUE THREAD

**Issue by Tukali** [SummerSec/ShiroAttack2#13]
选择爆破密钥，出现多个shiro场景的描述，无法爆破密钥
<img width="986" alt="CleanShot 2022-03-04 at 11 39 40@2x" src="https://user-images.githubusercontent.com/45891208/156695030-8177a9ed-7085-4553-861b-e1c1ba8ccfa8.png">

**Comment by lucksec** [comment]
同问

**Comment by murray-sky** [comment]
很多都会无法爆破，可以原版爆破出来，然后这个非得把其他工具爆破出来的，放进去单个识别，才显示key正确，而且我遇到一个站点，使用任何一个利用链都提示正确以及回显都提示正确，但是执行命令都没有返回，用了原版是可以的

**Comment by SummerSec** [comment]
面对这种情况两种解决方案：
1. 你把这个站发给我邮箱，我测试并修复改进。
2. 自己抓包，判断是否哪一个环节出现问题，然后尝试自己手动解决。现在这个shiro末年时代，现在能打的基本上都是疑难点，稀奇古怪的问题都会出现。

**Comment by SummerSec** [comment]
如果你们直接说问题了啥问题，我也没环境。无法复现，无法测试。
