### ISSUE TITLE
ShiroAttack2 4.5.2 版本检测失败，原版ShiroAttack 2.2成功执行

### ISSUE THREAD

**Issue by Asura88** [SummerSec/ShiroAttack2#14]
ShiroAttack2 4.5.2 版本检测失败，原版ShiroAttack 2.2成功执行

ShiroAttack2 4.5.2 版本

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/25000885/157178214-e63ae608-e373-4806-98d7-f0814539b3c7.png">

爆破过程速度慢，显示key是 

[++] 存在shiro框架！
[++] 找到key：kPH+bIxk5D2deZiIxcaaaA==
[+] 爆破结束

ShiroAttack 2.2

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/25000885/157178424-793e261e-8c98-47d3-887b-5fc83ec92a19.png">

爆破速度同样慢，但是准确，已经成功执行命令

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/25000885/157179539-48f3b11d-a989-4494-94ac-b0fbc914b875.png">

**Comment by Asura88** [comment]
人呢？

**Comment by SummerSec** [comment]
见https://github.com/SummerSec/ShiroAttack2/issues/16
