### ISSUE TITLE
change shiro key 失败

### ISSUE THREAD

**Issue by BonjourM3** [SummerSec/ShiroAttack2#17]
背景：vulfocus和vulhub的shiro靶场
工具版本：4.5.2
更改shiro key时提示注入失败，其他的内存马注入正常

**Comment by SummerSec** [comment]
https://github.com/SummerSec/AgentInjectTool 使用最新这款工具。

**Comment by BonjourM3** [comment]
> https://github.com/SummerSec/AgentInjectTool 使用最新这款工具。

好的，谢谢

**Comment by 0day4day** [comment]
> https://github.com/SummerSec/AgentInjectTool 使用最新这款工具。

使用这款工具还是没法改shiro key 看看AgentInjectTool  insue
