### ISSUE TITLE
1

### ISSUE THREAD

**Issue by greenbergpengliang** [SummerSec/ShiroAttack2#18]
能不能给个编译版本

**Comment by SummerSec** [comment]
releases页面下一直都有呀！？你这是什么问题？

**Comment by greenbergpengliang** [comment]
> releases页面下一直都有呀！？你这是什么问题？
大哥能不能教教怎么打包jar，二月份你不是更新了吗？

**Comment by SummerSec** [comment]
> > releases页面下一直都有呀！？你这是什么问题？
> > 大哥能不能教教怎么打包jar，二月份你不是更新了吗？

跟新内容不影响正常使用，打包jar这个百度就行了。
