### ISSUE TITLE
请问只能使用JDK8运行吗，JDK11无法爆破出密钥

### ISSUE THREAD

**Issue by mrr-yao** [SummerSec/ShiroAttack2#20]
![1650117996(1)](https://user-images.githubusercontent.com/78681164/163678039-47fce57a-70c3-402f-bf1d-d4ab2a0810dc.jpg)

**Comment by whami-root** [comment]
目前jdk8运行

**Comment by SummerSec** [comment]
是的，尽量使用Oracle jdk8
