### ISSUE TITLE
linux系统，启动jar包报错显示没有找到主类

### ISSUE THREAD

**Issue by MobaxTermX** [SummerSec/ShiroAttack2#26]
Could not find or load main class com.summersec.attack.UI.Mai

**Comment by 2021Kfzz1** [comment]
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (build 25.332-b09, mixed mode)

**Comment by myxss** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/33475775/232964686-341f1bfb-0245-425d-93be-3ca70c5aa681.png">
我也有同样的问题，请问你这边怎么解决的

**Comment by myxss** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/33475775/232964864-495a4f91-898b-4945-90d2-d53e7f347875.png">
