### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by spac3wh1te** [SummerSec/ShiroAttack2#31]
![image](https://user-images.githubusercontent.com/93125368/181530897-e72cdd0d-1dac-404f-af8e-c41bd6b69d9c.png)

/Users/white/Desktop/ShiroAttack2-master/src/main/java/com/summersec/attack/deser/payloads/CommonsBeanutilsAttrCompare.java:26:16
java: 找不到符号
  符号:   方法 setValues(com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl,java.lang.String,java.lang.String,java.lang.String)
  位置: 类型为com.sun.org.apache.xerces.internal.dom.AttrNSImpl的变量 attrNS1

java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

**Comment by spac3wh1te** [comment]
jdk1.8.0_301换成最新版的1.8.0_382 问题解决

**Comment by ki10Moc** [comment]
师傅你好，我换成openjdk1.8.0_382后，又显示缺少javafx的包

**Comment by wanswu** [comment]
> 1.8.0_382

https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/what-is-corretto-8.html
