### ISSUE TITLE
关于复杂请求

### ISSUE THREAD

**Issue by NeverDieSuddenly** [SummerSec/ShiroAttack2#33]
大佬能不能复杂请求直接是一个框啊
就像这样
![image](https://user-images.githubusercontent.com/67091104/183853710-3281a392-ce7f-4d27-89b5-8298ad2ac174.png)

现在工具上得复杂请求 我试了很长时间没有试成功，另外就是post数据支持json格式么？

**Comment by SummerSec** [comment]
https://github.com/SummerSec/ShiroAttack2/pull/36
