### ISSUE TITLE
自定义UA头？

### ISSUE THREAD

**Issue by Deep0** [SummerSec/ShiroAttack2#4]
直接用工具跑发现识别不出Shiro框架，代理进burp发现走的流量500或502 。
而直接用浏览器打开代理进burp正常。
然后更改了下header头正常了，猜测工具header头可能被封或者有些网站必须加一些header头才能访问。

**Comment by SummerSec** [comment]
这个会在下一个版本更新，下一个版本会采用随机的ua。如果可以，还有提交ua的。
