### ISSUE TITLE
注入内存马这个功能尤其是对于哥斯拉内存马注入了之后怎末用啊哥斯拉要密钥的呀，你这只有密码啊

### ISSUE THREAD

**Issue by halodoom** [SummerSec/ShiroAttack2#5]
注入内存马这个功能尤其是对于哥斯拉内存马注入了之后怎末用啊哥斯拉要密钥的呀，你这只有密码啊

**Comment by SummerSec** [comment]
> 注入内存马这个功能尤其是对于哥斯拉内存马注入了之后怎末用啊哥斯拉要密钥的呀，你这只有密码啊

建议使用冰蝎马，可以直接连接。

**Comment by SummerSec** [comment]
> 注入内存马这个功能尤其是对于哥斯拉内存马注入了之后怎末用啊哥斯拉要密钥的呀，你这只有密码啊

哥斯拉密钥应该是默认的

**Comment by halodoom** [comment]
> 

知道了老哥
