### ISSUE TITLE
有key无gadget

### ISSUE THREAD

**Issue by Baikeryoyo** [SummerSec/ShiroAttack2#6]
可以检测到默认key
但是检测不到利用链
这个是版本问题嘛

**Comment by SummerSec** [comment]
> 可以检测到默认key 但是检测不到利用链 这个是版本问题嘛

如果可以详情发送到c3N1bW1lcnNlY0BnbWFpbC5jb20=

**Comment by signfind** [comment]
水哥 带带我

**Comment by SummerSec** [comment]
> 水哥 带带我

别玩尬的
