### ISSUE TITLE
构造链问题

### ISSUE THREAD

**Issue by chenchenhen6** [SummerSec/ShiroAttack2#8]
师傅，我在复现fofa靶场http://vulfocus.fofa.so/的shiro721的时候发现
![image](https://user-images.githubusercontent.com/35289748/149974448-12aac80b-e78e-4b43-9a48-29de82101542.png)
这个工具找不到构造链
![image](https://user-images.githubusercontent.com/35289748/149974549-dd6d5c6a-02d0-4acb-a210-88d3482892ae.png)
但是我用回原版的工具是可以找到的
![image](https://user-images.githubusercontent.com/35289748/149974663-49ee01b3-c659-417f-b319-517c6a47936f.png)
麻烦帮忙看看是什么原因

**Comment by SummerSec** [comment]
我没有账号，能否提供一下？

**Comment by SummerSec** [comment]
如果可以请发送到邮箱c3N1bW1lcnNlY0BnbWFpbC5jb20=

**Comment by chenchenhen6** [comment]
师傅，发给你了，收到没

**Comment by SummerSec** [comment]
收到了

**Comment by SummerSec** [comment]
已经复现了，回头找一下原因。

**Comment by SummerSec** [comment]
不知道为什么，代码https://github.com/SummerSec/ShiroAttack2/compare/4.3...4.4 在几乎没有变化的两个版本之间也会有这个问题，但实际测试4.4只是多了一个修改key的功能。而4.4版本就不行，而4.3则是可以的。但在fofa搜索一样资产时，而没有影响。

**Comment by SummerSec** [comment]
我尝试了很多种方式去测试，4.4版本的判断方式也是一样的，抓包请求确实是没有特征。但目前最新版本的4.5.2版本的判断方式已经改了，也是不行。但在其他环境测试是可以的。所以目前这个bug，没有方法解决。大概率是特殊环境导致的。几乎可以忽略不记。如果需要，可以尝试使用4.3版本的。

**Comment by jhhd88** [comment]
我昨天测试过4.3-4.5.2所有版本，都没遇到过未能找到构造链的问题。

**Comment by SummerSec** [comment]
> 我昨天测试过4.3-4.5.2所有版本，都没遇到过未能找到构造链的问题。

这么玄学的吗？他的账号密码是测不到的。

**Comment by SummerSec** [comment]
> 我昨天测试过4.3-4.5.2所有版本，都没遇到过未能找到构造链的问题。

你也是fofa的靶场吗？

**Comment by jhhd88** [comment]
> > 我昨天测试过4.3-4.5.2所有版本，都没遇到过未能找到构造链的问题。
> 
> 你也是fofa的靶场吗？

我是昨天看到他提的问题，才去实验了一下。

**Comment by chenchenhen6** [comment]
是shiro721会这样，shiro550是正常的

**Comment by chenchenhen6** [comment]
我昨天使用的版本是4.5.1，会出现这样的问题

**Comment by jhhd88** [comment]
> 我昨天使用的版本是4.5.1，会出现这样的问题

难怪，我说呢，我刚试了，4.3是OK的，4.3以上不行

**Comment by jhhd88** [comment]
> 是shiro721会这样，shiro550是正常的

难怪，我说呢，我刚试了，4.3是OK的，4.3以上不行
